name: Deploy Angular App

on:
  push:
    branches:
      - main  # Adjust this according to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: 'mcarf.angular.cv'

      - name: Set OpenAI API Key
        run: |
          echo "export const environment = {" > mcarf.angular.cv/src/environments/environment.prod.ts
          echo "  production: true," >> mcarf.angular.cv/src/environments/environment.prod.ts
          echo "  openaiApiKey: '$OPENAI_API_KEY'" >> mcarf.angular.cv/src/environments/environment.prod.ts
          echo "};" >> mcarf.angular.cv/src/environments/environment.prod.ts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Build Angular app
        run: npm run build
        working-directory: 'mcarf.angular.cv'

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: mcarf.angular.cv/dist/mcarf.angular.cv/browser
          enable_jekyll: true
